// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoVxu3nyfFk0X1F1VNyeY6yhGijHVXVcU',
    appId: '1:889273735292:web:04d3f56c47334e593d91f9',
    messagingSenderId: '889273735292',
    projectId: 'polibus-1b2d9',
    authDomain: 'polibus-1b2d9.firebaseapp.com',
    storageBucket: 'polibus-1b2d9.firebasestorage.app',
    measurementId: 'G-Z11XRVF8GG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApF5WWUF69IlwcAGHcKwB2X6Xo_AhYL9s',
    appId: '1:889273735292:android:bbe2762c5fd7384a3d91f9',
    messagingSenderId: '889273735292',
    projectId: 'polibus-1b2d9',
    storageBucket: 'polibus-1b2d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIDC6nN09cmIDX8j0ypNm3Nkew56_bnRY',
    appId: '1:889273735292:ios:641e58169d7f57d03d91f9',
    messagingSenderId: '889273735292',
    projectId: 'polibus-1b2d9',
    storageBucket: 'polibus-1b2d9.firebasestorage.app',
    iosBundleId: 'com.example.polibus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIDC6nN09cmIDX8j0ypNm3Nkew56_bnRY',
    appId: '1:889273735292:ios:641e58169d7f57d03d91f9',
    messagingSenderId: '889273735292',
    projectId: 'polibus-1b2d9',
    storageBucket: 'polibus-1b2d9.firebasestorage.app',
    iosBundleId: 'com.example.polibus',
  );

}