// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfQt-gL6dvrPeTA2bqqk7f_LWUKC_8xpA',
    appId: '1:289730392059:web:d5ea4c2960a77deadf655e',
    messagingSenderId: '289730392059',
    projectId: 'react-603e6',
    authDomain: 'react-603e6.firebaseapp.com',
    databaseURL: 'https://react-603e6-default-rtdb.firebaseio.com',
    storageBucket: 'react-603e6.firebasestorage.app',
    measurementId: 'G-VGLDQWYJYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl0-0RHfSE6-b_gIsb79RMTM2O1jHwjZo',
    appId: '1:289730392059:android:04a314618f07e7fcdf655e',
    messagingSenderId: '289730392059',
    projectId: 'react-603e6',
    databaseURL: 'https://react-603e6-default-rtdb.firebaseio.com',
    storageBucket: 'react-603e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_1JnOYfIF1KO6yN-VC0jPBOl0vrbarow',
    appId: '1:289730392059:ios:3ccab8e74d45ef3edf655e',
    messagingSenderId: '289730392059',
    projectId: 'react-603e6',
    databaseURL: 'https://react-603e6-default-rtdb.firebaseio.com',
    storageBucket: 'react-603e6.firebasestorage.app',
    iosBundleId: 'com.example.polibus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_1JnOYfIF1KO6yN-VC0jPBOl0vrbarow',
    appId: '1:289730392059:ios:3ccab8e74d45ef3edf655e',
    messagingSenderId: '289730392059',
    projectId: 'react-603e6',
    databaseURL: 'https://react-603e6-default-rtdb.firebaseio.com',
    storageBucket: 'react-603e6.firebasestorage.app',
    iosBundleId: 'com.example.polibus',
  );
}
